TRI_LAYER_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
DYNAMIC_MACRO_ENABLE = yes
LEADER_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

SRC += features/custom_shift_keys.c
