// Copyright 2023 Danny Nguyen (danny@keeb.io)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define SPLIT_HAND_PIN GP4
#define USB_VBUS_PIN GP0
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13
#define SERIAL_USART_PIN_SWAP
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define I2C_DRIVER I2CD2
#define I2C1_SDA_PIN GP10
#define I2C1_SCL_PIN GP11

// BG
#define TAPPING_TERM 220
#define TAPPING_TERM_PER_KEY
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define SPLIT_LAYER_STATE_ENABLE
//#define RGB_MATRIX_LEDMAPS_ENABLED
//#define PERMISSIVE_HOLD
//#define HOLD_ON_OTHER_KEY_PRESS

// #define WS2812_DI_PIN D3
// #define RGBLED_NUM 14
// #define RGBLIGHT_LIMIT_VAL 200
// #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
// #define RGBLIGHT_DEFAULT_ON true
// #define RGBLIGHT_DEFAULT_HUE 0
// #define RGBLIGHT_DEFAULT_SAT UINT8_MAX
// #define RGBLIGHT_DEFAULT_VAL RGBLIGHT_LIMIT_VAL
// #define RGBLIGHT_LAYERS
// #define RGBLIGHT_SLEEP
//#define SPLIT_LAYER_STATE_ENABLE
// #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
// #define RGB_MATRIX_STARTUP_HUE 0
// #define RGB_MATRIX_STARTUP_SAT 0
// #define RGB_MATRIX_STARTUP_VAL 0
